language: python
python:
  - 3.5
  - 3.6
  - 3.7.5

install:
  - pip install pipenv
  - pipenv install --dev
script:
  - pyinstaller main.py --onefile --console

deploy:
  provider: dev,
  local_dir: build,
  github-token: $GITHUB_TOKEN,
  keep_history: true,
  skip-cleanup: true,
  target_branch: master
  on:
    branch: master