import os

HOME = os.environ["HOME"]
USER = os.environ["USERNAME"]
PROJECT_NAME = "openvpn-linux-gui"
PROJ_PATH = os.path.join(os.path.expanduser(f"~{USER}"), f"{PROJECT_NAME}")


PATH_TO_USER_FOLDER = os.path.join(PROJ_PATH, "user_conf")
USER_FOLDER = "user_conf"

PATH_TO_USER_CRED_FILE = os.path.join(PROJ_PATH, ".user_credentials")
USER_CRED_FILE = ".user_credentials"

PATH_TO_USER_PREF_FILE = os.path.join(PROJ_PATH, "user_pref.json")
USER_PREF_FILE = "user_pref.json"

PATH_TO_CACHE_FOLDER = os.path.join(PROJ_PATH, "cache_servers")
CACHE_FOLDER = "cache_servers"

PATH_TO_OVPN_FILE = os.path.join(PROJ_PATH, "server.ovpn")
OVPN_FILE = "server.ovpn"

PATH_TO_RESOLV_BACKUP_FILE = os.path.join(PROJ_PATH, ".resolv_conf_backup")
RESOLV_BACKUP_FILE = ".resolv_conf_backup"

PATH_TO_IPV6_BACKUP_FILE = os.path.join(PROJ_PATH, ".ipv6_backup")
IPV6_BACKUP_FILE = ".ipv6_backup"

SERVER_FILE_TYPE = ".json"
OS_PLATFORM = "linux"
DYNDNS_CHECK_URL = "http://checkip.dyndns.org"
PROTON_CHECK_URL = "https://api.protonmail.ch/vpn/location"
PROTON_SERVERS_URL = "https://api.protonmail.ch/vpn/logicals"
PROTON_HEADERS = {"x-pm-appversion": "Other", "x-pm-apiversion": "3", "Accept": "application/vnd.protonmail.v1+json"}
PROTON_DNS = "\n#Generated by GUI for ProtonVPN\nnameserver 10.8.8.1"
ON_BOOT_PROCESS_NAME = "openvpn-client@"+OVPN_FILE.split(".")[0].strip()
