import os

HOME = os.environ["HOME"]
USER = os.environ["USERNAME"]
PROJECT_NAME = "openvpn-linux-gui"
PROJ_PATH = os.path.join(os.path.expanduser(f"~{USER}"), f"{PROJECT_NAME}")

USER_FOLDER = os.path.join(PROJ_PATH, "user_conf")
USER_CRED_FILE = os.path.join(USER_FOLDER, ".user_credentials")
USER_PREF_FILE = os.path.join(USER_FOLDER, "user_pref.json")
CACHE_FOLDER = os.path.join(PROJ_PATH, "cache_servers")
OVPN_FILE = os.path.join(USER_FOLDER, "server.ovpn")
RESOLV_BACKUP_FILE = os.path.join(USER_FOLDER, ".resolv_conf_backup")
IPV6_BACKUP_FILE = os.path.join(USER_FOLDER, ".ipv6_backup")

SERVER_FILE_TYPE = ".json"
OS_PLATFORM = "linux"
DYNDNS_CHECK_URL = "http://checkip.dyndns.org"
PROTON_CHECK_URL = "https://api.protonmail.ch/vpn/location"
PROTON_SERVERS_URL = "https://api.protonmail.ch/vpn/logicals"
PROTON_HEADERS = {"x-pm-appversion": "Other", "x-pm-apiversion": "3", "Accept": "application/vnd.protonmail.v1+json"}
PROTON_DNS = "\n#Generated by openvpn-linux-gui for ProtonVPN\nnameserver 10.8.8.1"
ON_BOOT_PROCESS_NAME = "openvpn-client@"+OVPN_FILE.split("/")[-1].split(".")[0].strip()
