USER_FOLDER = "user_conf"
USER_CRED_FILE = ".user_credentials"
USER_PREF_FILE = "user_pref.json"
CACHE_FOLDER = "cache_servers"
OVPN_FILE = "connection.ovpn"
RESOLV_BACKUP_FILE = ".resolv_conf_backup"
IPV6_BACKUP_FILE = ".ipv6_backup"

SERVER_FILE_TYPE = ".json"
OS_PLATFORM = "linux"
DYNDNS_CHECK_URL = "http://checkip.dyndns.org"
PROTON_CHECK_URL = "https://api.protonmail.ch/vpn/location"
PROTON_SERVERS_URL = "https://api.protonmail.ch/vpn/logicals"
PROTON_HEADERS = {"x-pm-appversion": "Other", "x-pm-apiversion": "3", "Accept": "application/vnd.protonmail.v1+json"}
PROJECT_NAME = "openvpn-linux-gui"
PROTON_DNS = "\n#Generated by GUI for ProtonVPN\nnameserver 10.8.8.1"
ON_BOOT_PROCESS_NAME = "openvpn-client@"+OVPN_FILE.split(".")[0]
